/* Customer Journey Details/Content, Figma 1082:17955. Uses the existing Drawer,
 * tokens, controls and motion lifecycle; supplementary data is a local demo. */
(() => {
  'use strict';
  const anchors = [['about','О клиентском пути'],['assessment','Внутренняя оценка'],['benchmark','Бенчмаркинг, AI-CJM'],['additional','Дополнения']];
  const presets = [
    {number:'1232',title:'Приём и регистрация заявки — расчётной карты «Альта»',type:'Основной',tags:['ТОП 200','B2C'],efficiency:55.5,metrics:[['4',',88','positive'],['0',',68%','info'],['2',',10%','attention'],['22',',4%','info']]},
    {number:'1432',title:'Проверка параметров клиента — расчётной карты «Альта»',type:'Основной',tags:['ТОП 200','ТБ'],efficiency:61.1,metrics:[['4',',79','info'],['0',',35%','positive'],['1',',20%','info'],['—','','neutral']]},
    {number:'1432',title:'Формирование условий — расчётной карты «Альта»',type:'Основной',tags:['ТБ'],efficiency:70,metrics:[['4',',90','positive'],['0',',22%','positive'],['0',',61%','positive'],['16',',8%','positive']]},
    {number:'1232',title:'Подписание документов — расчётной карты «Альта»',type:'Дополнительный',tags:['ТБ'],efficiency:0,metrics:[['4',',42','danger'],['—','','neutral'],['3',',60%','danger'],['74',',5%','danger']]}
  ];
  const observations = [
    ['Количество экранов (3) совпадает с ведущими конкурентами — ВТБ, Ozon Банк, обеспечивая компактный и быстрый клиентский путь','В комментариях к оценкам (SCAT / NPS) клиенты выражают благодарности, говорят что всё работает отлично','Надежность процесса — 99,99% при допустимом уровне сбоев 0,05%, что соответствует лучшим отраслевым показателям'],
    ['На экране «Успех» отсутствует кнопка «Повторить перевод», поэтому клиентам, регулярно переводящим средства себе, приходится заново открывать процесс; также отображаются лишь сумма и счета без остатков, даты, времени и номера операции, в отличие от Т-Банка, где показываются полные детали','Относительно небольшое (0,01%) количество обращений связаны с увеличенными сроками переводов (если зачисление происходит не моментально), необходимостью получения подтверждающих документов по переводу (нет доступа с экрана успеха)','Размер комиссии не указывается, тогда как у конкурента (Т-Банк) клиенту явно сообщают, что перевод бесплатный, что повышает прозрачность']
  ];
  const internalCopy='Описываем в дескрипторе про то, что есть внутренняя оценка и по каким правилам входящего процесса или процессов она выстраивается и по какому лимиту... Как правило такой дескриптор содержит частичную методологию, которая подробно рассказывает о подсчёте эффективности и внутренней оценки';
  const metricLabels=['CSAT','Технические ошибки','Обращения','Отклонение по длительности'];
  function getProcesses(row) {
    // A real relationship list (including an empty one) always wins over fixtures.
    if (Array.isArray(row.linkedProcesses)) return row.linkedProcesses.map(record=>({...record,entity:'processes'}));
    return presets.map((item,index)=>({...item,metrics:item.metrics.map(metric=>[...metric]),tags:[...item.tags],id:`journey-demo-${row.id}-${index+1}`,entity:'processes',source:'journey-demo',owner:'Ковалевский Артём Андреевич',ownerRole:'Руководитель направления',block:row.block||'Транзакционный банкинг B2C',division:row.division||'Кредитные карты',date:row.date||'',status:row.status||'Исполняется',count:0}));
  }
  function renderSphere(value) {
    if(value===null||value===undefined||!Number.isFinite(Number(value)))return '<span class="jd-efficiency-unrated" aria-label="Эффективность не оценивалась">—</span>';
    const percent=Math.max(0,Math.min(100,Number(value)));
    const tone=percent>85?'positive':percent>65?'indigo':percent>45?'attention':'danger';
    const top=percent===0?-32:64*percent/100;
    return `<span class="jd-efficiency-glyph jd-efficiency--${tone}${percent===0?' jd-efficiency--zero':''}" data-efficiency-percent="${percent}" style="--jd-curtain-top:${top}px;--jd-curtain-height:${96-top}px" aria-hidden="true"><span class="jd-sphere-ball"></span>${percent<100?`<span class="jd-curtain"><span class="jd-blur-fallback"></span></span>`:''}</span>`;
  }
  function render(row,u) {
    const {esc,icon,tag}=u;
    const asset=(name,extra='')=>`<img class="pd-icon ${extra}" src="assets/journey-details/${name}.svg" alt="" width="24" height="24">`;
    const number=(whole,fraction='')=>`<span class="jd-number"${whole==='—'?'':` data-pd-motion-number="${esc(whole+fraction)}"`}><span data-pd-number-whole>${esc(whole)}</span><small data-pd-number-fraction>${esc(fraction)}</small></span>`;
    const person=(name,role='',compact=false)=>`<div class="jd-person${compact?' jd-person--compact':''}"><span class="pd-person-avatar">${icon('imgIcon24Person')}</span><div class="jd-person-copy"><p>${esc(name||'Не указан')}</p>${role?`<p class="jd-person-role">${esc(role)}</p>`:''}</div>${icon('imgIcon24Share','pd-icon-16')}</div>`;
    const score=(value,limit,tone='positive')=>`<span class="jd-score jd-score--${tone}"><span>${esc(value)}</span>${limit?`<small>/ ${esc(limit)}</small>`:''}</span>`;
    const id=row.numberSimulated?row.code:`КП ${row.number||'2026'}`;
    const heading=`<header class="pd-process-heading jd-heading"><div class="pd-heading-labels"><button class="pd-id-badge" data-pd-action="copy" data-pd-copy="${esc(id)}" aria-label="Скопировать ID ${esc(id)}">${esc(id)}${icon('imgIcon16Copy','pd-icon-16')}</button></div><div class="pd-title-actions"><h1 id="pd-title">${esc(row.title||'Выбор и оформление расчётной карты «Альта»')}</h1><div class="pd-process-actions"><button type="button" class="jd-icon-action" data-jd-show-summary aria-label="Показать синтез наблюдений">${asset('ai')}</button><button type="button" class="pd-action-button" data-pd-action="export" aria-label="Сохранить деталку КП в PDF">pdf ↓</button><button type="button" class="pd-action-button" data-pd-action="print">${icon('imgIcon24Print')}<span>Печать</span></button></div></div></header>`;
    const summary=`<section class="pd-ai-summary jd-synthesis" id="jd-observation-synthesis" aria-labelledby="jd-synthesis-title"><div class="jd-synthesis-heading">${asset('ai')}<h2 id="jd-synthesis-title">Синтез наблюдений</h2><button type="button" class="jd-icon-action" data-jd-dismiss-summary aria-label="Скрыть синтез наблюдений">${icon('imgIcon24Exit')}</button></div>${observations.map((items,i)=>`<div class="jd-observation-group">${asset(i?'risk':'positive')}<ul>${items.map(text=>`<li>${esc(text)}</li>`).join('')}</ul></div>`).join('')}</section>`;
    const metadata=`<article class="pd-overview-panel jd-metadata"><div class="jd-overview-tags">${tag('ТОП 200')}${tag('AI')}${tag('В редизайне','orange')}<span class="jd-technology-icons">${['ai','eye','benchmarking','monitoring','gemba'].map(name=>asset(name)).join('')}</span></div><div class="jd-field"><p class="pd-field-label">Рейтинг</p><div class="jd-rating">${score('4')}<span class="jd-leader">${asset('crown')}<span>Лидер процессного управления</span></span></div></div><div class="jd-field"><p class="pd-field-label">Владелец клиентского пути</p>${person(row.owner||'Иванов Иван Васильевич',row.ownerRole||'Сервисы для бизнеса',true)}</div><div class="jd-field"><p class="pd-field-label">Подразделение</p><p>${esc([row.block,row.division].filter(Boolean).join(' / ')||'Блок «Транзакционный банкинг B2C» / Дивизион «Кредитные карты»')}</p></div></article>`;
    // This overview is the agreed current Figma fixture (23.5%, September 2026).
    // Process relationships and identity above remain those of the selected row.
    const widget=`<article class="pd-overview-panel pd-efficiency-widget jd-widget" data-pd-motion-group="efficiency"><div class="pd-widget-heading"><p>Эффективность</p><p class="pd-widget-value"><span data-pd-motion-number="23,5%">23,5%</span></p></div><div class="pd-sphere-viewport" role="img" aria-label="Демонстрационная эффективность 23,5 процента"><div class="pd-large-sphere"><img class="pd-sphere-image" src="assets/journey-details/large-sphere-23.5.svg" width="154" height="154" alt=""><div class="pd-sphere-curtain"><span class="jd-large-blur-fallback"></span></div></div></div><div class="pd-period"><button type="button" class="pd-period-button" data-pd-action="period-prev" aria-label="Предыдущий месяц">${icon('imgChevronLeft','pd-chevron-left')}</button><span>Сентябрь, 2026</span><button type="button" class="pd-period-button" data-pd-action="period-next" aria-label="Следующий месяц">${icon('imgChevronRight','pd-chevron-right')}</button></div></article>`;
    const processes=getProcesses(row);
    const processCards=processes.map((process,index)=>{
      const metrics=process.metrics||metricLabels.map(()=>['—','','neutral']);
      const value=process.efficiency;
      const [whole,fraction]=value===null||value===undefined?['—',undefined]:Number(value).toFixed(1).split('.');
      const metric=(label,data)=>`<div class="jd-metric"><span class="jd-metric-label"><span>${esc(label)}</span>${icon('imgIcon16Info','pd-icon-16')}</span><span class="jd-metric-value jd-metric--${data[2]}">${number(data[0],data[1])}</span></div>`;
      const processId=`П ${process.number||''}`;
      return `<article class="jd-process-card" data-jd-process-card="${index}"${index?' data-jd-extra-process hidden':''}><div class="jd-process-header"><div class="jd-process-title-block"><div class="jd-process-tags"><button type="button" class="pd-id-badge" data-pd-action="copy" data-pd-copy="${esc(processId)}" aria-label="Скопировать ${esc(processId)}">${esc(processId)}${icon('imgIcon16Copy','pd-icon-16')}</button>${process.type?tag(process.type,process.type==='Основной'?'green':''):''}${(process.tags||[]).map(value=>tag(value)).join('')}</div><h3><button type="button" data-jd-process="${index}" class="jd-process-link">${esc(process.title)} <span aria-hidden="true">↗</span></button></h3></div>${person(process.owner,process.ownerRole|| (process.source==='journey-demo'?'Руководитель направления':''))}</div><div class="jd-process-indicators" data-pd-motion-group="journey-process"><div class="jd-process-efficiency"><span class="jd-sphere-slot">${renderSphere(value)}</span><div class="jd-metric"><span class="jd-metric-label">Эффективность ${icon('imgIcon16Info','pd-icon-16')}</span>${number(whole,fraction===undefined?'':','+fraction+'%')}</div>${asset('trend','jd-efficiency-trend')}</div>${metrics.map((data,i)=>metric(metricLabels[i],data)).join('')}</div></article>`;
    }).join('');
    const assessment=`<section class="pd-section jd-section" id="pd-assessment" aria-labelledby="jd-assessment-title"><div class="jd-section-heading"><h2 id="jd-assessment-title">Внутренняя оценка</h2>${score('62,2%','70%')}</div><div class="jd-section-content"><p class="jd-description">${esc(internalCopy)}</p><h3 class="jd-subheading">Включённые процессы <span class="pd-counter">${processes.length}</span></h3><div class="jd-process-list" id="jd-included-processes">${processCards||'<p class="pd-muted">У клиентского пути нет связанных процессов.</p>'}</div>${processes.length>1?`<div class="jd-section-footer"><button type="button" class="jd-more-link" data-jd-toggle-processes aria-controls="jd-included-processes" aria-expanded="false"><span data-jd-toggle-label>Показать все</span>${icon('chevron-down')}</button></div>`:''}</div></section>`;
    return `<div id="pd-about" class="jd-overview-block">${heading}${summary}<div class="jd-overview-grid">${metadata}${widget}</div></div>${assessment}${window.BpmJourneySupplement?.render(u)||''}<p class="pd-demo-note">Оценки, синтез наблюдений, бенчмаркинг и дополнительные метрики — демонстрационные данные макета. ${Array.isArray(row.linkedProcesses)?'Связи с процессами сохранены из Excel.':'Включённые процессы — пример из макета.'} Серверная часть не подключена.</p>`;
  }
  window.BpmJourneyDetails=Object.freeze({render,getProcesses,anchors,renderSphere});
})();
